steps:
  # 1. Download .env dari Cloud Storage
  # Ngambil data env yg disimpen di cloud storage pake gsuri
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://prak-tcc-projek-akhir/.env", ".env"]

  # 2. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--cache-from",
        "gcr.io/$PROJECT_ID/prak-tcc-projek-akhir",
        "-t",
        "gcr.io/$PROJECT_ID/prak-tcc-projek-akhir:${SHORT_SHA}",
        ".",
      ]

  # 3. Push ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/prak-tcc-projek-akhir:${SHORT_SHA}"]

  # 4. Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "prak-tcc-projek-akhir",
        "--image",
        "gcr.io/$PROJECT_ID/prak-tcc-projek-akhir:${SHORT_SHA}",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

# Log hanya akan disimpan di Google Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
