POST   http://localhost:5000/api/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword",
  "confirm_password": "testpassword"
}


###
DELETE http://localhost:5000/api/bookmark/2
Content-Type: application/json

